name: Add Resource
description: Propose a new resource for the directory
labels: ["new resource"]
body:
  - type: input
    id: title
    attributes:
      label: Resource Name
      placeholder: "Resource title"
    validations: { required: true }

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "One or two sentences"

  - type: input
    id: category
    attributes:
      label: Category
      placeholder: "e.g., Documentation, Tutorial, Research, ..."
    validations: { required: false }

  - type: dropdown
    id: target_age_group
    attributes:
      label: Target Age Group
      options: ["<10","10 – 14","14 – 18","18+"]
    validations: { required: false }

  - type: dropdown
    id: resource_type
    attributes:
      label: Resource Type
      options: ["publication","application","tool","other"]
    validations: { required: true }

  - type: input
    id: language
    attributes:
      label: Language
      placeholder: "e.g., English, German"

  - type: input
    id: url
    attributes:
      label: URL
      placeholder: "https://…"
    validations: { required: true }

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      multiple: true
      options: ["Web","Meta","Steam","Android","iOS","PICO","other"]

  - type: input
    id: publication_date
    attributes:
      label: Publication Date
      description: "YYYY-MM-DD"
      placeholder: "2025-11-05"
